### ISSUE TITLE
Include Post Category IDs in JS paywall() method settings

### ISSUE THREAD

**Issue by nickjohnson** [sabramedia/pigeonwp#6]
The goal is to include an array of post category ids as a setting in the `paywall()` method. The same place where `contentId` is set. The setting should be called `contentCatid`.

**Comment by MattGeri** [comment]
@nickjohnson I've added the code here: https://github.com/sabramedia/pigeonwp/commit/b8f689264af8c414a1276ed1d0b8736ddff2eab5

I called the field `contentCategories` as `contentCatid`didn't make sense as there could be multiple categories in the array. Is that ok?

I've also updated the version but have not deployed it to WP yet. If there are any other features you want to add before we deploy, let me know.

**Comment by nickjohnson** [comment]
This looks good. I did something like this in wp.pigeon.io and it worked marvelously. Can we can go ahead and get this pushed to production.
